Algoritmo "semnome"
// Autor(a)    : BIANCA REBECA DE LIMA BARROS
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis 
   N1, N2, N3: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("indique o primeiro seguimento de reta: ")
    leia(N1)
    escreva("indique o segundo seguimento de reta: ")
    leia(N2)
    escreva("indique o segundo segmento de reta: ")
    leia(N3)
Fimalgoritmo
