Algoritmo "semnome"
// Autor(a)    : BIANCA REBECA DE LIMA BARROS
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
   N1: real
   N2: real
   M: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Insira sua primeira nota: ")
   leia(N1)
   escreva("Insira sua segunda nota: ")
   leia(N2)
   M <- (N1+ N2)/ 2
   escreva("Sua média final será igual a ", M)

Fimalgoritmo