Algoritmo "semnome"
// Autor(a)    : BIANCA REBECA DE LIMA BARROS
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
   NA: inteiro
   N1: inteiro
   NS: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("INDIQUE UM NÚMERO: ")
   leia(N1)
   NA <- N1- 1
   escreva("o antecessor do algarismo escolhido é ", NA)
   NS <- N1+ 1
   escreva(", já seu sucessor, ", NS)
Fimalgoritmo