Algoritmo "semnome"
// Autor(a)    : BIANCA REBECA DE LIMA BARROS
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
   DINDIN: real
   DOL: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("INDIQUE A QUANTIDADE DE DINHEIRO CONTIDA EM SUA CARTEIRA: ")
   leia(DINDIN)
   DOL <- DINDIN/5.24
   escreva("Após a conversão, seu recurso monetário passará a ser de ", DOL, " dólares.")
Fimalgoritmo