Algoritmo "semnome"
// Autor(a)    : BIANCA REBECA DE LIMA BARROS
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis 
   S, AU: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("indique qual é seu salário mensal: ")
    leia(S)
    AU <- S* 115/100
    escreva("com um aumento de 15%, seu salário passará a ser de ", AU, " reais.")
Fimalgoritmo