Algoritmo "semnome"
// Autor(a)    : BIANCA REBECA DE LIMA BARROS
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis 
   DIAS, SALARIO: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Indique o número de dias que você trabalha por mês: ")
    leia(DIAS)
    SALARIO <- 200* DIAS
    escreva("No final do mês, seu salário será de: ", SALARIO)
Fimalgoritmo